version: "3"
services:
    app:
        build:
            context: ./
            dockerfile: dockerfiles/app/Dockerfile
        volumes:            
            - "./:/var/www"
        links:
          - redis
        ports:
          - "8080:81"
          - "5180:5173"
    redis:
      image: redis:5.0

    postgres:
      image: postgres:latest
      ports:
        - 5440:5432
      volumes:
        - ~/apps/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=1234
        - POSTGRES_USER=user
        - POSTGRES_DB=base01