name: Run Laravel Backend Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Install Composer Dependencies
        run: |
          docker exec -T backend-container-name composer install --prefer-dist --no-progress --no-suggest

      - name: Set up Environment
        run: |
          docker exec -T backend-container-name cp .env.example .env
          docker exec -T backend-container-name php artisan key:generate

      - name: Run Migrations (Optional)
        run: |
          docker exec -T backend-container-name php artisan migrate --force

      - name: Run Backend Tests
        run: |
          docker exec -T backend-container-name php artisan test

      - name: Shut down Docker Compose
        run: |
          docker-compose -f Scrum/backend/docker-compose.yml down
